name: SentimentAnalysis

channels:
  - pytorch
  - conda-forge

dependencies:
  - python==3.7
  - numpy
  - scipy
  - ipython
  - jupyter
  - cython
  - pip
  - pytorch
  - torchvision
  - torchtext

